### ISSUE TITLE
custom launcher.jar feature doesn't  work

### ISSUE THREAD

**Issue by skerman** [orfjackal/idea-sbt-plugin#105]
Clicking the Start button in the SBT console ignores custom launcher.jar location.  Evidently it always looks for c:\program files x86\sbt\sbt-launch.jar even tho a different location is specified in the sbt settings.

I have closed and reopened Idea but no luck.

14.1.1 on Win 7.

![image](https://cloud.githubusercontent.com/assets/2931425/7256684/a6de5e20-e81e-11e4-8659-6bd084bdb711.png)

![image](https://cloud.githubusercontent.com/assets/2931425/7256699/bd9ffb1e-e81e-11e4-97f3-b13ec67445bc.png)

**Comment by retronym** [comment]
That configuration UI is for JetBrain's native SBT support (now part of the Scala plugin).

This plugin predates that support. It has its own settings for the launcher JAR in `Other Settings -> SBT`

![image](https://cloud.githubusercontent.com/assets/65551/7265650/7b775fb2-e8e0-11e4-9314-2e69dfe21feb.png)

I hope that the native support is expanded over time to make this plugin obsolete. Right now, the main feature missing is the console.

**Comment by skerman** [comment]
Thanks,


[cid:image004.png@01D07CDF.72A34BC0]
